version: "3"

services:
  coordinatorz:
    container_name: coordinatorz
    image: 513838501479.dkr.ecr.ap-northeast-1.amazonaws.com/cch-coordinator:latest
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
    command: >
      sh -c 'cp -a /root/data/coordinatorz/n0/simappcli /root/cli && goreman -f /root/Procfile --set-ports=false -exit-on-error=true start'
    environment:
      - CHAIN_ID=coordinatorz
      - CONTRACT_MODE=
    volumes:
      - coordinatorz_data:/root/cli

  securityz:
    container_name: securityz
    image: 513838501479.dkr.ecr.ap-northeast-1.amazonaws.com/cch-security:latest
    ports:
      - "26659-26660:26656-26657"
      - "1318:1317"
    command: >
      sh -c 'cp -a /root/data/securityz/n0/simappcli /root/cli && goreman -f /root/Procfile --set-ports=false -exit-on-error=true start'
    environment:
      - CHAIN_ID=securityz
      - CONTRACT_MODE=estate
    volumes:
      - securityz_data:/root/cli

  coinz:
    container_name: coinz
    image: 513838501479.dkr.ecr.ap-northeast-1.amazonaws.com/cch-coin:latest
    ports:
      - "26661-26662:26656-26657"
      - "1319:1317"
    command: >
      sh -c 'cp -a /root/data/coinz/n0/simappcli /root/cli && goreman -f /root/Procfile --set-ports=false -exit-on-error=true start'
    environment:
      - CHAIN_ID=coinz
      - CONTRACT_MODE=dcc
    volumes:
      - coinz_data:/root/cli

  initializer:
    container_name: initializer
    image: 513838501479.dkr.ecr.ap-northeast-1.amazonaws.com/cch-initializer:latest
    volumes:
      - coordinatorz_data:/root/cli/coordinatorz:ro
      - securityz_data:/root/cli/securityz:ro
      - coinz_data:/root/cli/coinz:ro

  relayer0:
    container_name: relayer0
    image: 513838501479.dkr.ecr.ap-northeast-1.amazonaws.com/cch-relayer:latest
    command: >
      bash -c 'bash /root/data/init-relayer.sh coordinatorz-coinz && rly --home /root/.relayer -d start coordinatorz-coinz'
    volumes:
      - ./data:/root/data

  relayer1:
    container_name: relayer1
    image: 513838501479.dkr.ecr.ap-northeast-1.amazonaws.com/cch-relayer:latest
    command: >
      bash -c 'bash /root/data/init-relayer.sh coordinatorz-securityz && rly --home /root/.relayer -d start coordinatorz-securityz'
    volumes:
      - ./data:/root/data

  api:
    container_name: api
    hostname: api
    image: 513838501479.dkr.ecr.ap-northeast-1.amazonaws.com/cch-api:latest
    working_dir: /root/api
    environment:
      - DB_PATH=/root/api/sqlite/demo.db
    ports:
      - 8080:8080
    command: >
      bash -c 'make setup-db && apiserver'
    volumes:
      - api_data:/root/api/sqlite

volumes:
  coordinatorz_data:
    driver_opts:
      type: none
      device: $PWD/data/cli/coordinatorz
      o: bind
  securityz_data:
    driver_opts:
      type: none
      device: $PWD/data/cli/securityz
      o: bind
  coinz_data:
    driver_opts:
      type: none
      device: $PWD/data/cli/coinz
      o: bind
  api_data:
    driver_opts:
      type: none
      device: $PWD/data/api
      o: bind
