version: '3'

services:
  coordinatorz:
    container_name: coordinatorz
    build:
      context: ./chain
      args:
        - CHAIN_ID=coordinatorz
        - REPO_URL=https://github.com/datachainlab/cross
    ports:
      - "26656-26657:26656-26657"
    command: >
      sh -c 'cp -a /root/data/coordinatorz/n0/simappcli /root/cli && simappd --home /root/data/coordinatorz/n0/simappd start --pruning=nothing'
    volumes:
      - ./data/cli/coordinatorz:/root/cli

  securityz:
    container_name: securityz
    build:
      context: ./chain
      args:
        - CHAIN_ID=securityz
        - REPO_URL=https://github.com/datachainlab/cross
    ports:
      - "26659-26660:26656-26657"
    command: >
      sh -c 'cp -a /root/data/securityz/n0/simappcli /root/cli && simappd --home /root/data/securityz/n0/simappd start --pruning=nothing'
    volumes:
      - ./data/cli/securityz:/root/cli

  coinz:
    container_name: coinz
    build:
      context: ./chain
      args:
        - CHAIN_ID=coinz
        - REPO_URL=https://github.com/datachainlab/cross
    ports:
      - "26661-26662:26656-26657"
    command: >
      sh -c 'cp -a /root/data/coinz/n0/simappcli /root/cli && simappd --home /root/data/coinz/n0/simappd start --pruning=nothing'
    volumes:
      - ./data/cli/coinz:/root/cli

  relayer0:
    container_name: relayer0
    build:
        context: ./relayer
    command: >
      bash -c 'bash /root/data/init-relayer.sh coordinatorz-coinz && rly --home /root/.relayer -d start coordinatorz-coinz'
    volumes:
      - ./data:/root/data

  relayer1:
    container_name: relayer1
    build:
        context: ./relayer
    command: >
      bash -c 'bash /root/data/init-relayer.sh coordinatorz-securityz && rly --home /root/.relayer -d start coordinatorz-securityz'
    volumes:
      - ./data:/root/data
