version: '3'

services:
  coordinatorz:
    container_name: coordinatorz
    build:
      context: ./chain
      args:
        - CHAIN_ID=coordinatorz
        - REPO_URL=https://github.com/datachainlab/cross
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
    command: >
      sh -c 'cp -a /root/data/coordinatorz/n0/simappcli /root/cli && goreman -f /root/Procfile --set-ports=false -exit-on-error=true start'
    environment:
      - CHAIN_ID=coordinatorz
      - CONTRACT_MODE=
    volumes:
      - ./data/cli/coordinatorz:/root/cli

  securityz:
    container_name: securityz
    build:
      context: ./chain
      args:
        - CHAIN_ID=securityz
        - REPO_URL=https://github.com/datachainlab/cross
    ports:
      - "26659-26660:26656-26657"
      - "1318:1317"
    command: >
      sh -c 'cp -a /root/data/securityz/n0/simappcli /root/cli && goreman -f /root/Procfile --set-ports=false -exit-on-error=true start'
    environment:
      - CHAIN_ID=securityz
      - CONTRACT_MODE=hotel
    volumes:
      - ./data/cli/securityz:/root/cli

  coinz:
    container_name: coinz
    build:
      context: ./chain
      args:
        - CHAIN_ID=coinz
        - REPO_URL=https://github.com/datachainlab/cross
    ports:
      - "26661-26662:26656-26657"
      - "1319:1317"
    command: >
      sh -c 'cp -a /root/data/coinz/n0/simappcli /root/cli && goreman -f /root/Procfile --set-ports=false -exit-on-error=true start'
    environment:
      - CHAIN_ID=coinz
      - CONTRACT_MODE=train
    volumes:
      - ./data/cli/coinz:/root/cli

  relayer0:
    container_name: relayer0
    build:
        context: ./relayer
    command: >
      bash -c 'bash /root/data/init-relayer.sh coordinatorz-coinz && rly --home /root/.relayer -d start coordinatorz-coinz'
    volumes:
      - ./data:/root/data

  relayer1:
    container_name: relayer1
    build:
        context: ./relayer
    command: >
      bash -c 'bash /root/data/init-relayer.sh coordinatorz-securityz && rly --home /root/.relayer -d start coordinatorz-securityz'
    volumes:
      - ./data:/root/data

  api:
    container_name: api
    hostname: api
    working_dir: /root/api
    ports:
      - 8080:8080
    build:
      context: ./api
    command: >
      bash -c 'make migrate-up && ./scripts/initdata.sh && DB_PATH=/root/api/demo.db apiserver'
