# for docker-compose
node:
  coordinator:
    addr: "http://coordinatorz:1317"
    chainId: "coordinatorz"
  security:
    addr: "http://securityz:1317"
    chainId: "securityz"
  coin:
    addr: "http://coinz:1317"
    chainId: "coinz"
path:
  coordinator-coin:
    port: "cross"
    channel: "ibconexfer"
  coordinator-security:
    port: "cross"
    channel: "ibctwoxfer"
contract:
  coin:
    id: "dcc"
  security:
    id: "estate"
job:
  durationSec: 10
